language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: KMUDUWbR89fJfxVqtses6Xc+NKP705FNwxWm4UWqdK1THkWUGMSD26A43ySGuhzqnZMOe3aih9goSeu5AGvyWWEzXT4Eg17Ko0CnRk3G7qoZl7mBHZFFAFQ9OrFBm0tUGJCPiqCGVqw5T9sUC0SRZrpByy0MLX1WplokDdn1GDYj1Fiy0iWKxcwcjs8nuJUm4k1JE0HkAl2MzO4o1ek0cE5EKVEcO1DcMCDzPpPkKXkpdjRJbV6dtjWdm69qnDEIJokK2rhJAPwrlfCEoVbcNim1cH6ihw7iLDFBm8WDqUqLFTZzdwTg6ZTIRF2F/coMVDEVsbk2EP20L0h3/OLuw4TEA/vT+M0MehZkHxCr53GajZUoDKGTlHs/7es7W2QEWdXmDlnEFRyYAIm0vv89aTu+zAB0yAHc1xMwQfCOe8K9aiAnc2yNGv0CE/xseAUFbRFh/RJDh4gt8puAHPanTe+pYP3DqPA2NNDdb4YPoY9HNYlkRcOecBMmV1kQk1xp5+X9imImDOyRvmrG39Krtr34Gw0ilh1yfhKEktuRo3kPfgD0s7MiHFJMBrUod1isxD/GWzSAHJDxd08ha47kPL4m7PhHX+eVY5vIgXdHEKOTC1BJRQMOlxgBX22lZGYKC3H1yXOTrigL+0HNGcEUx+G2Ubd1zhDlLEHHDj24kbI=
  app: daily-app-5-3-19
