language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- --coverage --coverageReporters=text-lcov | coveralls
deploy:
  provider: heroku
  api_key:
    secure: P5PPw40TNYEgxsxHrHSmmRkngOmhnOM7zFFiE2GE/mrqTT0fkS7sQigubBAxJXrVNUgoZr1eGOUDanhznACBdHSz/W/AF2X53g7xavtKb+9PEK4vb3Hl+PokdM2lAY+YXoGg+Jdbp7LSK+BGd/NfZXlWrOMcYTBFMbbGIpOKYucon9N/9AkLLQYmc+lTthTnGNDG8waoQfwnZ1LYvN83mvvY1bY/Y8MZ4VoGTo8OjaNYcH9jMTidAhYziiq5rjhgzoxDEgMrtalMWLLnaIoLIerXf3ffGU0IFjdbUF1gbihmwZwHcyH/Q7TOA6cl3w0psY/sJqVlf2VROsCYuPGlJggJY7+Cx6jmcNMcw8ujmiQDwoetHo/83zzUQ7UvIwzzZA3a8h/iF46jtwkHdYe7lRHF/05J1sb64qVZ3hM5B/4z/PnIrpmbpNlXlBtlTH7DeP4PQQw5H8y0x0qwnSHl0dmU72J6I9YPq8bSweq/GatU3DLyq0EuoP4qzQ4ngMaZaUifbN2S6gNdL22xqPYUD7s2H8b8T3D9BjqO0yvEaCP9P5JjDaaJeyt4SpB7eBerVhUcx0YgezyXnUTUI1Z6CXmGrvP9pTVGR7JF+uwT/ckKLyO5lmIqO0sVgRWuHlf3B3vV/0XoSuOgmRwzPBERevKlV5St3cUXb7c2wx0Nu/g=
  app: daily-app-5-3-19
